// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_type.proto

#include "key_type.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace adb {
namespace proto {
}  // namespace proto
}  // namespace adb
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_key_5ftype_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_key_5ftype_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_key_5ftype_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_key_5ftype_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_key_5ftype_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016key_type.proto\022\tadb.proto*\027\n\007KeyType\022\014"
  "\n\010RSA_2048\020\000B-\n\035com.android.server.adb.p"
  "rotosB\014KeyTypeProtob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_key_5ftype_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_key_5ftype_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_key_5ftype_2eproto_once;
static bool descriptor_table_key_5ftype_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_key_5ftype_2eproto = {
  &descriptor_table_key_5ftype_2eproto_initialized, descriptor_table_protodef_key_5ftype_2eproto, "key_type.proto", 107,
  &descriptor_table_key_5ftype_2eproto_once, descriptor_table_key_5ftype_2eproto_sccs, descriptor_table_key_5ftype_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_key_5ftype_2eproto::offsets,
  file_level_metadata_key_5ftype_2eproto, 0, file_level_enum_descriptors_key_5ftype_2eproto, file_level_service_descriptors_key_5ftype_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_key_5ftype_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_key_5ftype_2eproto), true);
namespace adb {
namespace proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_key_5ftype_2eproto);
  return file_level_enum_descriptors_key_5ftype_2eproto[0];
}
bool KeyType_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace adb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
